title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
exclude:
  - docker-compose.yml
  - package.json
  - package-lock.json
  - postcss.config.js
  - README.md
  - setup.sh
  - tailwind.config.js
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Build settings
plugins:
  - jekyll-postcss
#  - jekyll_sqlite

postcss:
  cache: false
# sqlite:
#   - data: places
#     file: _db/db.sqlite
#     query: SELECT * FROM place
